### ISSUE TITLE
Have you considered a high performance schema driven approach?

### ISSUE THREAD

**Issue by ntucker** [klis87/normy#23]
[@data-client/normalizr](https://www.npmjs.com/package/@data-client/normalizr) creates type safe definitions automatically and handles many different data models like [Unions](https://dataclient.io/rest/api/Union and allows [pushing](https://dataclient.io/rest/api/Collection#usage) or [unshift](https://dataclient.io/rest/api/Collection#unshift) to Arrays.

**Comment by klis87** [comment]
Closing as mentioned library just uses an alternative, not compatible approach.
