### ISSUE TITLE
Optimistic updates with a custom cache ID

### ISSUE THREAD

**Issue by ehynds** [klis87/normy#24]
Thanks for the great library!

I have a custom `normalizerConfig` that uses a `contextId` property on an object if it exists for the cache key, otherwise falls back to `id`.

Note that `contextId` is really only used as the cache ID; these objects also have a `id` property but it's not guaranteed to be unique across tenants in my multi-tenant use case; `contextId` is a compound key that makes it truly unique across all caches.

```tsx
<QueryNormalizerProvider
  queryClient={queryClient}
  normalizerConfig={{
    getNormalizationObjectKey: (obj) => {
      if ('contextId' in obj && typeof obj.contextId === 'string') {
        return obj.contextId;
      }
      return typeof obj.id === 'string' ? obj.id : undefined;
    },
  }}
>
  ...
</QueryNormalizerProvider>
```

Now, when I go to optimistically update one of these entities keyed by `contextId`, I'm noticing that the `id` value of my entity is being overwritten by the `id` property returned from `optimisticData`:

```tsx
onMutate: () => {
  return {
    optimisticData: {
      id: contextId,
      isFollowing: true,
    },
    rollbackData: {
      id: contextId,
      isFollowing: false,
    },
  };
},
```

What I thought this code was saying is "find the object in the cache keyed by the value `contextId` and set its `isFollowing` property to `true`". I did not expect the `id` property of the entity itself to also be overwritten, which in my case creates unintended UI bugs.

Is what I'm trying to achieve possible?

**Comment by ehynds** [comment]
Thanks, that does work. How does the library know which record to find in the cache?

The fact that `id` isn't a special property and that it's able to find a record to optimistically update on `contextId` alone, while ignoring `isFollowing: true` as part of that lookup, is confusing to me.

**Comment by klis87** [comment]
Just by executing `getNormalizationObjectKey`.

This function is used when inspecting queries and normalizing data, as well as when reading mutation data, to know which objects to update.

For example, you could also have `getNormalizationObjectKey: obj => obj._id as string | undefined`,

Then, you would do:
```js
onMutate: () => {
  return {
    optimisticData: {
      _id: 1,
      isFollowing: true,
    },
    rollbackData: {
      _id: 1,
      isFollowing: false,
    },
  };
},
```

Think about it in another way:
1) When having a response data from a mutation, you would get an object with normal id and normal contextId, not id as contextId, so if you manually prepare optimistic data, think what would you get from API
2) For this library to work, objects have to have consistent object structure, and using contextId as id is a violation for this rule.

**Comment by klis87** [comment]
> update on contextId alone, while ignoring isFollowing: true as part of that lookup, is confusing to me.

To find a proper object to update, the object has to contain all attributes needed to calculate an unique identifier. It should also contain at least those attributes there, which could change, in your case `isFollowing`, which will be merged with the corresponding object in normalized store. Ofc this could be a nested obejct as well, or object containing arrays, even with other normalized nodes with own ids, it will work, as deep as you need, as long as the object structure is consistent.

**Comment by ehynds** [comment]
That makes sense, thank you!
