### ISSUE TITLE
 workspace dependency "@normy/core" not found

### ISSUE THREAD

**Issue by garrettg123** [klis87/normy#9]
This happens when installing via bun.sh

**Comment by klis87** [comment]
I am not sure in what context you tried install it? I guess you cloned this repo and tried to install it locally with bun?

**Comment by klis87** [comment]
I see. I did not use bun, but it seems that you want to install this project on your machine, not install `@normy/react-query` in your own project.

If that is the case, you should use the tools which this project use. normy uses `pnpm` as package manager, perhaps `Bun` is not compatible. Plus, I am not sure about lock files compatibility.

**Comment by klis87** [comment]
I used 
```
  "dependencies": {
    "@normy/core": "workspace:~"
  },
```
for a reason, as I want `~` in resulted dependencies. `*` is translated to exact dependency and I prefer to be more flexible with versions.

**Comment by klis87** [comment]
In the furure I am going actually to switch to `^`, as I will not make any breaking changes for update like 1.1.0 > 1.2.0, but I will do this after version 1 is released.

**Comment by klis87** [comment]
That is very weird because pnpm install works for me in this repo examples :thinking:

**Comment by klis87** [comment]
Actually it was indeed the bug. I do not know how it happened, but I had core dependency fixed instead of using `workspace:*`. It might have sth to do with a lerna crash. Now it should work, including with `shadcn`
